name: Build and Package

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # Run workflow on version tags, e.g. v1.0.0
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev

      - name: Configure and build
        run: |
          mkdir -p build && cd build
          cmake ..
          make -j$(nproc)

      - name: Build Debian package
        run: |
          cd build
          cmake -DCPACK_GENERATOR=DEB ..
          make -j$(nproc)
          cpack

      - name: Run tests
        run: |
          cd build
          if [ -f tests ]; then
            ./tests
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: s3-file-uploader
          path: |
            build/s3_file_uploader
            build/*.deb

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: s3-file-uploader
          path: artifacts

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            artifacts/s3_file_uploader
            artifacts/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
